name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint

  test:
    name: Test
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build addon
        run: yarn build
        working-directory: addon
      - name: Run Tests
        run: yarn test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: ['lint', 'test']
    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized
    steps:
      - uses: actions/checkout@master
      - name: Install Node
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        working-directory: test-app
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
