name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint

  test:
    name: Test
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build addon
        run: yarn build
        working-directory: addon
      - name: Run Tests
        run: yarn test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: ["lint", "test"]
    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-release
          - ember-classic
          - embroider-safe
          - embroider-optimized
        # include: # Uncomment after it tests pass.
        #   - try-scenario: ember-canary
        #   - try-scenario: ember-beta
        #     allow-failure: true
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Build addon
        working-directory: addon
        run: yarn build
      - name: Run Tests
        working-directory: test-app
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
